### ISSUE TITLE
404 not found for .debug.css on tryscroll website

### ISSUE THREAD

**Issue by btheado** [breck7/tryscroll#5]
Follow this link and see the 404 in browser console for https://try.scroll.pub/.debug.css:

https://try.scroll.pub/#scroll%0A%20theme%20gazette%0A%20code%0A%20%20two%20%3D%201%20%2B%201%0A%20debugAbove

The debug output is not very readable without the css.

**Comment by breck7** [comment]
Whoops! Forgot to check it in.

Just pushed a fix:

https://github.com/breck7/tryscroll/commit/b792fe8f2cd0919895587e392859408e181e4bca

Thanks!

**Comment by btheado** [comment]
Looks good now. Thanks!

**Comment by breck7** [comment]
Thank you for the report! Keep the feedback coming!
